/// Flutter icons DBSandsteinIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DBSandsteinIcons
///      fonts:
///       - asset: fonts/DBSandsteinIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DBSandsteinIcons {
  DBSandsteinIcons._();

  static const _kFontFam = 'DBSandsteinIcons';
  static const String? _kFontPkg = null;

  static const IconData fisch = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frosch = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ausruf = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ring = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ringe = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tot = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData totenk = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wink = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puke = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gipfelgr = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gipfelm = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gipfeln = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muell = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quacke = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
